name: "Chromatic"

on:
  push:
    branches:
      - master
    paths:
      - "packages/ui/**"
  pull_request:
    paths:
      - "packages/ui/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install ui dependencies
        run: cd packages/ui && npm i

      - name: Install Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Publish to Chromatic
        id: chromatic_publish
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          exitZeroOnChanges: true
          workingDir: packages/ui
      - name: Run Storybook Tests
        run: |
          cd packages/ui
          npx playwright install --with-deps
          npm run storybook:accessibility:ci
        env:
          TARGET_URL: "${{ steps.chromatic_publish.outputs.storybookUrl }}"